/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiRecommendation {
  'title' : string,
  'mangaDexId' : string,
  'matchScore' : number,
  'reason' : string,
}
export interface BotCommand {
  'id' : bigint,
  'userId' : Principal,
  'command' : string,
  'response' : string,
  'timestamp' : bigint,
}
export type ContentType = { 'manga' : null } |
  { 'manhwa' : null } |
  { 'comics' : null };
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'upgrade' : [] | [boolean],
  'status_code' : number,
}
export interface MangaMeta {
  'status' : string,
  'coverImageUrl' : string,
  'title' : string,
  'contentType' : ContentType,
  'mangaDexId' : string,
  'description' : string,
  'author' : string,
  'genres' : Array<string>,
  'lastFetched' : bigint,
  'artist' : string,
  'rating' : number,
}
export interface MangaSearchResult {
  'status' : string,
  'coverImageUrl' : string,
  'title' : string,
  'contentType' : ContentType,
  'mangaDexId' : string,
  'description' : string,
  'author' : string,
  'genres' : Array<string>,
  'artist' : string,
  'rating' : number,
}
export type MessageDirection = { 'inbound' : null } |
  { 'outbound' : null };
export interface NewChapterNotification {
  'whatsappMessage' : string,
  'newChapter' : number,
  'title' : string,
  'mangaDexId' : string,
  'previousChapter' : number,
  'notifyAt' : bigint,
}
export type NotificationFrequency = { 'immediate' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface NotificationPrefs {
  'enabled' : boolean,
  'whatsappNumber' : string,
  'frequency' : NotificationFrequency,
  'webhookUrl' : string,
}
export type ReadingStatus = { 'reading' : null } |
  { 'dropped' : null } |
  { 'completed' : null } |
  { 'planToRead' : null };
export interface RecommendationProfile {
  'readingPatternNotes' : string,
  'preferredGenres' : Array<string>,
  'lastRecommendedAt' : bigint,
  'pastRecommendations' : Array<string>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WatchlistEntry {
  'title' : string,
  'contentType' : ContentType,
  'chaptersRead' : bigint,
  'mangaDexId' : string,
  'updatedAt' : bigint,
  'addedAt' : bigint,
  'lastKnownChapter' : number,
  'readingStatus' : ReadingStatus,
}
export interface WhatsAppMessage {
  'id' : string,
  'to' : string,
  'direction' : MessageDirection,
  'body' : string,
  'from' : string,
  'timestamp' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[WatchlistEntry], undefined>,
  'checkForNewChapters' : ActorMethod<[string], Array<NewChapterNotification>>,
  'clearWhatsAppChatHistory' : ActorMethod<[], undefined>,
  'fetchMangaMeta' : ActorMethod<[string], [] | [MangaMeta]>,
  'getAiRecommendations' : ActorMethod<[], Array<AiRecommendation>>,
  'getBotCommandLog' : ActorMethod<[bigint], Array<BotCommand>>,
  'getCachedAiRecommendations' : ActorMethod<[], Array<AiRecommendation>>,
  'getCachedMangaMeta' : ActorMethod<[string], [] | [MangaMeta]>,
  'getNotificationPrefs' : ActorMethod<[], [] | [NotificationPrefs]>,
  'getRecommendationProfile' : ActorMethod<[], [] | [RecommendationProfile]>,
  'getTrendingManga' : ActorMethod<[], Array<MangaSearchResult>>,
  'getTwilioConfig' : ActorMethod<
    [],
    {
      'accountSid' : string,
      'sandboxNumber' : string,
      'authTokenMasked' : string,
    }
  >,
  'getWatchlist' : ActorMethod<[], Array<WatchlistEntry>>,
  'getWhatsAppChatHistory' : ActorMethod<[], Array<WhatsAppMessage>>,
  /**
   * / Handle GET/HEAD — upgrade POST requests to update calls.
   */
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'http_request_update' : ActorMethod<[HttpRequest], HttpResponse>,
  'logBotCommand' : ActorMethod<[string, string], bigint>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'searchManga' : ActorMethod<[string], Array<MangaSearchResult>>,
  'setNotificationPrefs' : ActorMethod<[NotificationPrefs], undefined>,
  'setTwilioConfig' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transform_twilio' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateReadingProgress' : ActorMethod<
    [string, bigint, ReadingStatus],
    undefined
  >,
  'updateRecommendationProfile' : ActorMethod<
    [RecommendationProfile],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];