/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentType = IDL.Variant({
  'manga' : IDL.Null,
  'manhwa' : IDL.Null,
  'comics' : IDL.Null,
});
export const ReadingStatus = IDL.Variant({
  'reading' : IDL.Null,
  'dropped' : IDL.Null,
  'completed' : IDL.Null,
  'planToRead' : IDL.Null,
});
export const WatchlistEntry = IDL.Record({
  'title' : IDL.Text,
  'contentType' : ContentType,
  'chaptersRead' : IDL.Nat,
  'mangaDexId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'addedAt' : IDL.Int,
  'lastKnownChapter' : IDL.Float64,
  'readingStatus' : ReadingStatus,
});
export const NewChapterNotification = IDL.Record({
  'whatsappMessage' : IDL.Text,
  'newChapter' : IDL.Float64,
  'title' : IDL.Text,
  'mangaDexId' : IDL.Text,
  'previousChapter' : IDL.Float64,
  'notifyAt' : IDL.Int,
});
export const MangaMeta = IDL.Record({
  'status' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'mangaDexId' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'lastFetched' : IDL.Int,
  'artist' : IDL.Text,
  'rating' : IDL.Float64,
});
export const AiRecommendation = IDL.Record({
  'title' : IDL.Text,
  'mangaDexId' : IDL.Text,
  'matchScore' : IDL.Float64,
  'reason' : IDL.Text,
});
export const BotCommand = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'command' : IDL.Text,
  'response' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const NotificationFrequency = IDL.Variant({
  'immediate' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const NotificationPrefs = IDL.Record({
  'enabled' : IDL.Bool,
  'whatsappNumber' : IDL.Text,
  'frequency' : NotificationFrequency,
  'webhookUrl' : IDL.Text,
});
export const RecommendationProfile = IDL.Record({
  'readingPatternNotes' : IDL.Text,
  'preferredGenres' : IDL.Vec(IDL.Text),
  'lastRecommendedAt' : IDL.Int,
  'pastRecommendations' : IDL.Vec(IDL.Text),
});
export const MangaSearchResult = IDL.Record({
  'status' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'mangaDexId' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'artist' : IDL.Text,
  'rating' : IDL.Float64,
});
export const MessageDirection = IDL.Variant({
  'inbound' : IDL.Null,
  'outbound' : IDL.Null,
});
export const WhatsAppMessage = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Text,
  'direction' : MessageDirection,
  'body' : IDL.Text,
  'from' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'upgrade' : IDL.Opt(IDL.Bool),
  'status_code' : IDL.Nat16,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([WatchlistEntry], [], []),
  'checkForNewChapters' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NewChapterNotification)],
      [],
    ),
  'clearWhatsAppChatHistory' : IDL.Func([], [], []),
  'fetchMangaMeta' : IDL.Func([IDL.Text], [IDL.Opt(MangaMeta)], []),
  'getAiRecommendations' : IDL.Func([], [IDL.Vec(AiRecommendation)], []),
  'getBotCommandLog' : IDL.Func([IDL.Nat], [IDL.Vec(BotCommand)], ['query']),
  'getCachedAiRecommendations' : IDL.Func(
      [],
      [IDL.Vec(AiRecommendation)],
      ['query'],
    ),
  'getCachedMangaMeta' : IDL.Func([IDL.Text], [IDL.Opt(MangaMeta)], ['query']),
  'getNotificationPrefs' : IDL.Func(
      [],
      [IDL.Opt(NotificationPrefs)],
      ['query'],
    ),
  'getRecommendationProfile' : IDL.Func(
      [],
      [IDL.Opt(RecommendationProfile)],
      ['query'],
    ),
  'getTrendingManga' : IDL.Func([], [IDL.Vec(MangaSearchResult)], []),
  'getTwilioConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'accountSid' : IDL.Text,
          'sandboxNumber' : IDL.Text,
          'authTokenMasked' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
  'getWhatsAppChatHistory' : IDL.Func(
      [],
      [IDL.Vec(WhatsAppMessage)],
      ['query'],
    ),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'http_request_update' : IDL.Func([HttpRequest], [HttpResponse], []),
  'logBotCommand' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'searchManga' : IDL.Func([IDL.Text], [IDL.Vec(MangaSearchResult)], []),
  'setNotificationPrefs' : IDL.Func([NotificationPrefs], [], []),
  'setTwilioConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transform_twilio' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateReadingProgress' : IDL.Func(
      [IDL.Text, IDL.Nat, ReadingStatus],
      [],
      [],
    ),
  'updateRecommendationProfile' : IDL.Func([RecommendationProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentType = IDL.Variant({
    'manga' : IDL.Null,
    'manhwa' : IDL.Null,
    'comics' : IDL.Null,
  });
  const ReadingStatus = IDL.Variant({
    'reading' : IDL.Null,
    'dropped' : IDL.Null,
    'completed' : IDL.Null,
    'planToRead' : IDL.Null,
  });
  const WatchlistEntry = IDL.Record({
    'title' : IDL.Text,
    'contentType' : ContentType,
    'chaptersRead' : IDL.Nat,
    'mangaDexId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'addedAt' : IDL.Int,
    'lastKnownChapter' : IDL.Float64,
    'readingStatus' : ReadingStatus,
  });
  const NewChapterNotification = IDL.Record({
    'whatsappMessage' : IDL.Text,
    'newChapter' : IDL.Float64,
    'title' : IDL.Text,
    'mangaDexId' : IDL.Text,
    'previousChapter' : IDL.Float64,
    'notifyAt' : IDL.Int,
  });
  const MangaMeta = IDL.Record({
    'status' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'mangaDexId' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'lastFetched' : IDL.Int,
    'artist' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const AiRecommendation = IDL.Record({
    'title' : IDL.Text,
    'mangaDexId' : IDL.Text,
    'matchScore' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const BotCommand = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'command' : IDL.Text,
    'response' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const NotificationFrequency = IDL.Variant({
    'immediate' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const NotificationPrefs = IDL.Record({
    'enabled' : IDL.Bool,
    'whatsappNumber' : IDL.Text,
    'frequency' : NotificationFrequency,
    'webhookUrl' : IDL.Text,
  });
  const RecommendationProfile = IDL.Record({
    'readingPatternNotes' : IDL.Text,
    'preferredGenres' : IDL.Vec(IDL.Text),
    'lastRecommendedAt' : IDL.Int,
    'pastRecommendations' : IDL.Vec(IDL.Text),
  });
  const MangaSearchResult = IDL.Record({
    'status' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'mangaDexId' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'artist' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const MessageDirection = IDL.Variant({
    'inbound' : IDL.Null,
    'outbound' : IDL.Null,
  });
  const WhatsAppMessage = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Text,
    'direction' : MessageDirection,
    'body' : IDL.Text,
    'from' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'upgrade' : IDL.Opt(IDL.Bool),
    'status_code' : IDL.Nat16,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addToWatchlist' : IDL.Func([WatchlistEntry], [], []),
    'checkForNewChapters' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewChapterNotification)],
        [],
      ),
    'clearWhatsAppChatHistory' : IDL.Func([], [], []),
    'fetchMangaMeta' : IDL.Func([IDL.Text], [IDL.Opt(MangaMeta)], []),
    'getAiRecommendations' : IDL.Func([], [IDL.Vec(AiRecommendation)], []),
    'getBotCommandLog' : IDL.Func([IDL.Nat], [IDL.Vec(BotCommand)], ['query']),
    'getCachedAiRecommendations' : IDL.Func(
        [],
        [IDL.Vec(AiRecommendation)],
        ['query'],
      ),
    'getCachedMangaMeta' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MangaMeta)],
        ['query'],
      ),
    'getNotificationPrefs' : IDL.Func(
        [],
        [IDL.Opt(NotificationPrefs)],
        ['query'],
      ),
    'getRecommendationProfile' : IDL.Func(
        [],
        [IDL.Opt(RecommendationProfile)],
        ['query'],
      ),
    'getTrendingManga' : IDL.Func([], [IDL.Vec(MangaSearchResult)], []),
    'getTwilioConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'accountSid' : IDL.Text,
            'sandboxNumber' : IDL.Text,
            'authTokenMasked' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
    'getWhatsAppChatHistory' : IDL.Func(
        [],
        [IDL.Vec(WhatsAppMessage)],
        ['query'],
      ),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'http_request_update' : IDL.Func([HttpRequest], [HttpResponse], []),
    'logBotCommand' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'searchManga' : IDL.Func([IDL.Text], [IDL.Vec(MangaSearchResult)], []),
    'setNotificationPrefs' : IDL.Func([NotificationPrefs], [], []),
    'setTwilioConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transform_twilio' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateReadingProgress' : IDL.Func(
        [IDL.Text, IDL.Nat, ReadingStatus],
        [],
        [],
      ),
    'updateRecommendationProfile' : IDL.Func([RecommendationProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };