/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AiRecommendation {
    title: string;
    mangaDexId: string;
    matchScore: number;
    reason: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MangaSearchResult {
    status: string;
    coverImageUrl: string;
    title: string;
    contentType: ContentType;
    mangaDexId: string;
    description: string;
    author: string;
    genres: Array<string>;
    artist: string;
    rating: number;
}
export interface MangaMeta {
    status: string;
    coverImageUrl: string;
    title: string;
    contentType: ContentType;
    mangaDexId: string;
    description: string;
    author: string;
    genres: Array<string>;
    lastFetched: bigint;
    artist: string;
    rating: number;
}
export interface RecommendationProfile {
    readingPatternNotes: string;
    preferredGenres: Array<string>;
    lastRecommendedAt: bigint;
    pastRecommendations: Array<string>;
}
export interface WhatsAppMessage {
    id: string;
    to: string;
    direction: MessageDirection;
    body: string;
    from: string;
    timestamp: bigint;
}
export interface NewChapterNotification {
    whatsappMessage: string;
    newChapter: number;
    title: string;
    mangaDexId: string;
    previousChapter: number;
    notifyAt: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BotCommand {
    id: bigint;
    userId: Principal;
    command: string;
    response: string;
    timestamp: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<[string, string]>;
    upgrade?: boolean;
    status_code: number;
}
export interface WatchlistEntry {
    title: string;
    contentType: ContentType;
    chaptersRead: bigint;
    mangaDexId: string;
    updatedAt: bigint;
    addedAt: bigint;
    lastKnownChapter: number;
    readingStatus: ReadingStatus;
}
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<[string, string]>;
}
export interface NotificationPrefs {
    enabled: boolean;
    whatsappNumber: string;
    frequency: NotificationFrequency;
    webhookUrl: string;
}
export enum ContentType {
    manga = "manga",
    manhwa = "manhwa",
    comics = "comics"
}
export enum MessageDirection {
    inbound = "inbound",
    outbound = "outbound"
}
export enum NotificationFrequency {
    immediate = "immediate",
    daily = "daily",
    weekly = "weekly"
}
export enum ReadingStatus {
    reading = "reading",
    dropped = "dropped",
    completed = "completed",
    planToRead = "planToRead"
}
export interface backendInterface {
    addToWatchlist(entry: WatchlistEntry): Promise<void>;
    checkForNewChapters(mangaDexId: string): Promise<Array<NewChapterNotification>>;
    clearWhatsAppChatHistory(): Promise<void>;
    fetchMangaMeta(mangaDexId: string): Promise<MangaMeta | null>;
    getAiRecommendations(): Promise<Array<AiRecommendation>>;
    getBotCommandLog(limit: bigint): Promise<Array<BotCommand>>;
    getCachedAiRecommendations(): Promise<Array<AiRecommendation>>;
    getCachedMangaMeta(mangaDexId: string): Promise<MangaMeta | null>;
    getNotificationPrefs(): Promise<NotificationPrefs | null>;
    getRecommendationProfile(): Promise<RecommendationProfile | null>;
    getTrendingManga(): Promise<Array<MangaSearchResult>>;
    getTwilioConfig(): Promise<{
        accountSid: string;
        sandboxNumber: string;
        authTokenMasked: string;
    }>;
    getWatchlist(): Promise<Array<WatchlistEntry>>;
    getWhatsAppChatHistory(): Promise<Array<WhatsAppMessage>>;
    /**
     * / Handle GET/HEAD — upgrade POST requests to update calls.
     */
    http_request(req: HttpRequest): Promise<HttpResponse>;
    http_request_update(req: HttpRequest): Promise<HttpResponse>;
    logBotCommand(command: string, response: string): Promise<bigint>;
    removeFromWatchlist(mangaDexId: string): Promise<void>;
    searchManga(titleQuery: string): Promise<Array<MangaSearchResult>>;
    setNotificationPrefs(prefs: NotificationPrefs): Promise<void>;
    setTwilioConfig(accountSid: string, authToken: string, sandboxNumber: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    transform_twilio(input: TransformationInput): Promise<TransformationOutput>;
    updateReadingProgress(mangaDexId: string, chaptersRead: bigint, status: ReadingStatus): Promise<void>;
    updateRecommendationProfile(profile: RecommendationProfile): Promise<void>;
}
import type { ContentType as _ContentType, HttpResponse as _HttpResponse, MangaMeta as _MangaMeta, MangaSearchResult as _MangaSearchResult, MessageDirection as _MessageDirection, NotificationFrequency as _NotificationFrequency, NotificationPrefs as _NotificationPrefs, ReadingStatus as _ReadingStatus, RecommendationProfile as _RecommendationProfile, WatchlistEntry as _WatchlistEntry, WhatsAppMessage as _WhatsAppMessage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWatchlist(arg0: WatchlistEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(to_candid_WatchlistEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(to_candid_WatchlistEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async checkForNewChapters(arg0: string): Promise<Array<NewChapterNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.checkForNewChapters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkForNewChapters(arg0);
            return result;
        }
    }
    async clearWhatsAppChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearWhatsAppChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearWhatsAppChatHistory();
            return result;
        }
    }
    async fetchMangaMeta(arg0: string): Promise<MangaMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchMangaMeta(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchMangaMeta(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAiRecommendations(): Promise<Array<AiRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiRecommendations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiRecommendations();
            return result;
        }
    }
    async getBotCommandLog(arg0: bigint): Promise<Array<BotCommand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBotCommandLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBotCommandLog(arg0);
            return result;
        }
    }
    async getCachedAiRecommendations(): Promise<Array<AiRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedAiRecommendations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedAiRecommendations();
            return result;
        }
    }
    async getCachedMangaMeta(arg0: string): Promise<MangaMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedMangaMeta(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedMangaMeta(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationPrefs(): Promise<NotificationPrefs | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationPrefs();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationPrefs();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendationProfile(): Promise<RecommendationProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendationProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendationProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingManga(): Promise<Array<MangaSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingManga();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingManga();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTwilioConfig(): Promise<{
        accountSid: string;
        sandboxNumber: string;
        authTokenMasked: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTwilioConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTwilioConfig();
            return result;
        }
    }
    async getWatchlist(): Promise<Array<WatchlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhatsAppChatHistory(): Promise<Array<WhatsAppMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhatsAppChatHistory();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhatsAppChatHistory();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.http_request(arg0);
                return from_candid_HttpResponse_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.http_request(arg0);
            return from_candid_HttpResponse_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async http_request_update(arg0: HttpRequest): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.http_request_update(arg0);
                return from_candid_HttpResponse_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.http_request_update(arg0);
            return from_candid_HttpResponse_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async logBotCommand(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logBotCommand(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logBotCommand(arg0, arg1);
            return result;
        }
    }
    async removeFromWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async searchManga(arg0: string): Promise<Array<MangaSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchManga(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchManga(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async setNotificationPrefs(arg0: NotificationPrefs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNotificationPrefs(to_candid_NotificationPrefs_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNotificationPrefs(to_candid_NotificationPrefs_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setTwilioConfig(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTwilioConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTwilioConfig(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async transform_twilio(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform_twilio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform_twilio(arg0);
            return result;
        }
    }
    async updateReadingProgress(arg0: string, arg1: bigint, arg2: ReadingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReadingProgress(arg0, arg1, to_candid_ReadingStatus_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReadingProgress(arg0, arg1, to_candid_ReadingStatus_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateRecommendationProfile(arg0: RecommendationProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecommendationProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecommendationProfile(arg0);
            return result;
        }
    }
}
function from_candid_ContentType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HttpResponse_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HttpResponse): HttpResponse {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_MangaMeta_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MangaMeta): MangaMeta {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MangaSearchResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MangaSearchResult): MangaSearchResult {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MessageDirection_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageDirection): MessageDirection {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationFrequency_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationFrequency): NotificationFrequency {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPrefs_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPrefs): NotificationPrefs {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ReadingStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReadingStatus): ReadingStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_WatchlistEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchlistEntry): WatchlistEntry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_WhatsAppMessage_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WhatsAppMessage): WhatsAppMessage {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotificationPrefs]): NotificationPrefs | null {
    return value.length === 0 ? null : from_candid_NotificationPrefs_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecommendationProfile]): RecommendationProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MangaMeta]): MangaMeta | null {
    return value.length === 0 ? null : from_candid_MangaMeta_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enabled: boolean;
    whatsappNumber: string;
    frequency: _NotificationFrequency;
    webhookUrl: string;
}): {
    enabled: boolean;
    whatsappNumber: string;
    frequency: NotificationFrequency;
    webhookUrl: string;
} {
    return {
        enabled: value.enabled,
        whatsappNumber: value.whatsappNumber,
        frequency: from_candid_NotificationFrequency_n15(_uploadFile, _downloadFile, value.frequency),
        webhookUrl: value.webhookUrl
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    coverImageUrl: string;
    title: string;
    contentType: _ContentType;
    mangaDexId: string;
    description: string;
    author: string;
    genres: Array<string>;
    artist: string;
    rating: number;
}): {
    status: string;
    coverImageUrl: string;
    title: string;
    contentType: ContentType;
    mangaDexId: string;
    description: string;
    author: string;
    genres: Array<string>;
    artist: string;
    rating: number;
} {
    return {
        status: value.status,
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        contentType: from_candid_ContentType_n10(_uploadFile, _downloadFile, value.contentType),
        mangaDexId: value.mangaDexId,
        description: value.description,
        author: value.author,
        genres: value.genres,
        artist: value.artist,
        rating: value.rating
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contentType: _ContentType;
    chaptersRead: bigint;
    mangaDexId: string;
    updatedAt: bigint;
    addedAt: bigint;
    lastKnownChapter: number;
    readingStatus: _ReadingStatus;
}): {
    title: string;
    contentType: ContentType;
    chaptersRead: bigint;
    mangaDexId: string;
    updatedAt: bigint;
    addedAt: bigint;
    lastKnownChapter: number;
    readingStatus: ReadingStatus;
} {
    return {
        title: value.title,
        contentType: from_candid_ContentType_n10(_uploadFile, _downloadFile, value.contentType),
        chaptersRead: value.chaptersRead,
        mangaDexId: value.mangaDexId,
        updatedAt: value.updatedAt,
        addedAt: value.addedAt,
        lastKnownChapter: value.lastKnownChapter,
        readingStatus: from_candid_ReadingStatus_n24(_uploadFile, _downloadFile, value.readingStatus)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    to: string;
    direction: _MessageDirection;
    body: string;
    from: string;
    timestamp: bigint;
}): {
    id: string;
    to: string;
    direction: MessageDirection;
    body: string;
    from: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        to: value.to,
        direction: from_candid_MessageDirection_n29(_uploadFile, _downloadFile, value.direction),
        body: value.body,
        from: value.from,
        timestamp: value.timestamp
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    body: Uint8Array;
    headers: Array<[string, string]>;
    upgrade: [] | [boolean];
    status_code: number;
}): {
    body: Uint8Array;
    headers: Array<[string, string]>;
    upgrade?: boolean;
    status_code: number;
} {
    return {
        body: value.body,
        headers: value.headers,
        upgrade: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.upgrade)),
        status_code: value.status_code
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    coverImageUrl: string;
    title: string;
    contentType: _ContentType;
    mangaDexId: string;
    description: string;
    author: string;
    genres: Array<string>;
    lastFetched: bigint;
    artist: string;
    rating: number;
}): {
    status: string;
    coverImageUrl: string;
    title: string;
    contentType: ContentType;
    mangaDexId: string;
    description: string;
    author: string;
    genres: Array<string>;
    lastFetched: bigint;
    artist: string;
    rating: number;
} {
    return {
        status: value.status,
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        contentType: from_candid_ContentType_n10(_uploadFile, _downloadFile, value.contentType),
        mangaDexId: value.mangaDexId,
        description: value.description,
        author: value.author,
        genres: value.genres,
        lastFetched: value.lastFetched,
        artist: value.artist,
        rating: value.rating
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manga: null;
} | {
    manhwa: null;
} | {
    comics: null;
}): ContentType {
    return "manga" in value ? ContentType.manga : "manhwa" in value ? ContentType.manhwa : "comics" in value ? ContentType.comics : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    immediate: null;
} | {
    daily: null;
} | {
    weekly: null;
}): NotificationFrequency {
    return "immediate" in value ? NotificationFrequency.immediate : "daily" in value ? NotificationFrequency.daily : "weekly" in value ? NotificationFrequency.weekly : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reading: null;
} | {
    dropped: null;
} | {
    completed: null;
} | {
    planToRead: null;
}): ReadingStatus {
    return "reading" in value ? ReadingStatus.reading : "dropped" in value ? ReadingStatus.dropped : "completed" in value ? ReadingStatus.completed : "planToRead" in value ? ReadingStatus.planToRead : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inbound: null;
} | {
    outbound: null;
}): MessageDirection {
    return "inbound" in value ? MessageDirection.inbound : "outbound" in value ? MessageDirection.outbound : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MangaSearchResult>): Array<MangaSearchResult> {
    return value.map((x)=>from_candid_MangaSearchResult_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WatchlistEntry>): Array<WatchlistEntry> {
    return value.map((x)=>from_candid_WatchlistEntry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WhatsAppMessage>): Array<WhatsAppMessage> {
    return value.map((x)=>from_candid_WhatsAppMessage_n27(_uploadFile, _downloadFile, x));
}
function to_candid_ContentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationFrequency_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationFrequency): _NotificationFrequency {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationPrefs_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationPrefs): _NotificationPrefs {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_ReadingStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReadingStatus): _ReadingStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_WatchlistEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WatchlistEntry): _WatchlistEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contentType: ContentType;
    chaptersRead: bigint;
    mangaDexId: string;
    updatedAt: bigint;
    addedAt: bigint;
    lastKnownChapter: number;
    readingStatus: ReadingStatus;
}): {
    title: string;
    contentType: _ContentType;
    chaptersRead: bigint;
    mangaDexId: string;
    updatedAt: bigint;
    addedAt: bigint;
    lastKnownChapter: number;
    readingStatus: _ReadingStatus;
} {
    return {
        title: value.title,
        contentType: to_candid_ContentType_n3(_uploadFile, _downloadFile, value.contentType),
        chaptersRead: value.chaptersRead,
        mangaDexId: value.mangaDexId,
        updatedAt: value.updatedAt,
        addedAt: value.addedAt,
        lastKnownChapter: value.lastKnownChapter,
        readingStatus: to_candid_ReadingStatus_n5(_uploadFile, _downloadFile, value.readingStatus)
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enabled: boolean;
    whatsappNumber: string;
    frequency: NotificationFrequency;
    webhookUrl: string;
}): {
    enabled: boolean;
    whatsappNumber: string;
    frequency: _NotificationFrequency;
    webhookUrl: string;
} {
    return {
        enabled: value.enabled,
        whatsappNumber: value.whatsappNumber,
        frequency: to_candid_NotificationFrequency_n36(_uploadFile, _downloadFile, value.frequency),
        webhookUrl: value.webhookUrl
    };
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationFrequency): {
    immediate: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == NotificationFrequency.immediate ? {
        immediate: null
    } : value == NotificationFrequency.daily ? {
        daily: null
    } : value == NotificationFrequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    manga: null;
} | {
    manhwa: null;
} | {
    comics: null;
} {
    return value == ContentType.manga ? {
        manga: null
    } : value == ContentType.manhwa ? {
        manhwa: null
    } : value == ContentType.comics ? {
        comics: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReadingStatus): {
    reading: null;
} | {
    dropped: null;
} | {
    completed: null;
} | {
    planToRead: null;
} {
    return value == ReadingStatus.reading ? {
        reading: null
    } : value == ReadingStatus.dropped ? {
        dropped: null
    } : value == ReadingStatus.completed ? {
        completed: null
    } : value == ReadingStatus.planToRead ? {
        planToRead: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
